"""
This is the state definition for the AI.
It defines the state of the agent and the state of the conversation.
"""

from typing import Dict, List, Literal, NotRequired, TypedDict
from langgraph.graph import MessagesState

class Resource(TypedDict):
    """
    Represents a resource. Give it a good title and a short description.
    Can be either a web resource or a Tako chart.
    """
    url: str
    title: str
    description: str
    resource_type: NotRequired[Literal["web", "tako_chart"]]
    card_id: NotRequired[str]  # Tako card identifier for visualizations
    iframe_html: NotRequired[str]
    source: NotRequired[str]
    embed_url: NotRequired[str]  # Tako embed URL for iframe src

class DataQuestion(TypedDict):
    """
    Represents a structured data question with search configuration.
    """
    question: str
    search_effort: Literal["fast", "deep"]
    query_type: Literal["basic", "complex", "prediction_market"]

class Log(TypedDict):
    """
    Represents a log of an action performed by the agent.
    """
    message: str
    done: bool

class A2UIComponent(TypedDict):
    """
    Represents a declarative UI component generated by the agent (A2UI standard).
    """
    type: str   # stat_card | comparison_table | data_grid | timeline | kpi_row
    title: str
    data: dict
    source: NotRequired[str]

class ChartSpec(TypedDict):
    """
    Represents an ECharts visualisation spec streamed to the frontend.
    """
    id: str
    title: str
    option: dict   # Full ECharts option object
    source: NotRequired[str]

class AgentState(MessagesState):
    """
    This is the state of the agent.
    It is a subclass of the MessagesState class from langgraph.
    """
    model: str
    research_question: str
    search_sources: NotRequired[List[str]]
    report: str
    resources: List[Resource]
    logs: List[Log]
    data_questions: NotRequired[List[DataQuestion]]
    explore_context: NotRequired[str]
    critic_retry_count: NotRequired[int]
    pending_a2ui: NotRequired[List[A2UIComponent]]
    charts: NotRequired[List[ChartSpec]]
    suggested_questions: NotRequired[List[str]]
    delete_confirmation: NotRequired[str]         # "YES"/"NO" answered via the delete interrupt
    chart_reject_count: NotRequired[int]          # ungrounded-chart rejections this thread (capped)
    report_redirect_count: NotRequired[int]       # times pushed to WriteReport after answering in chat (capped)
    extracted_numerics: NotRequired[List[dict]]   # accumulated NumericFact dicts from all searches
    chart_datasets: NotRequired[List[dict]]       # chart-ready datasets from ExtractNumerics
    citations: NotRequired[Dict[str, dict]]       # "1" → {url, title, snippet}
